# Generated by Django 5.2 on 2025-04-16 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0002_shorturl_time_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='time_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
