# Generated by Django 5.2 on 2025-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0003_alter_shorturl_time_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=10000),
        ),
    ]
